# Generated by Django 2.2.5 on 2020-08-10 08:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.City')),
            ],
        ),
        migrations.CreateModel(
            name='Evacuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evacuation_site', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('flood', models.CharField(max_length=255)),
                ('landslides', models.CharField(max_length=255)),
                ('storm_surge', models.CharField(max_length=255)),
                ('earthquake', models.CharField(max_length=255)),
                ('tsunami', models.CharField(max_length=255)),
                ('massive_fire', models.CharField(max_length=255)),
                ('inland_flooding', models.CharField(max_length=255)),
                ('volcanic_phenomena', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('zipcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_zipcode', to='world.Zipcode')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Pref'),
        ),
    ]
