# Generated by Django 2.2.5 on 2020-08-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='evacuation_name',
        ),
    ]
