# Generated by Django 2.2.5 on 2020-08-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_remove_post_evacuation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='evacuation_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Evacuation'),
        ),
    ]
